### ISSUE TITLE
python error on qgis 2.6

### ISSUE THREAD

**Issue by gioman** [geodrinx/rasmover#4]
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/rasmover/rasmover.py", line 201, in canvasReleaseEvent
    f1   = open(fileVRT, 'r')
IOError: [Errno 2] No such file or directory: '\home\giovanni\.qgis2\python\plugins\rasmover\temp\original.vrt'

this happens on both Linux and Windows.

**Comment by geodrinx** [comment]
You have used  the developer  https://github.com/geodrinx/rasmover/archive/master.zip   instead of current    http://plugins.qgis.org/plugins/rasmover/   QGIS plugin  installable  version.

Please, install    rasmover   from  QGIS   "Plugins" > "Manage and Install Plugins..."   menu  panel.

Your error depended  from the lack of the "temp"  folder inside the developer ZIP .

**Comment by gioman** [comment]
Hi,
I haven't used the master version of rasmover, it was installed using the QGIS plugins repository, using QGIS plugin manager. The plugin installed using the plugins repository _has_ the "temp" folder in it, but it still throw the error. Reopening?

**Comment by gioman** [comment]
There is something wrong with the substitutions like

out_folder = out_folder.replace("\","/")
and 

fileVRT = fileVRT.replace("/","\")

if I comment those line the error goes away and the plugin seems to work. Anyway I'm not understanding how it works, do you have a tutorial or a screencast?

**Comment by gioman** [comment]
Oh, I see something working, but only on Windows. On Linux clicking and dragging the mouse has no effect. Should I open another ticket?

**Comment by geodrinx** [comment]
Yes, please.   But, anyway, insert also you Linux version:  any version, a different error...  ;)

**Comment by gioman** [comment]
I'm sorry but does not seems a Linux issue. The problem is that your code under Linux writes the string called "stringazza" the wrong way, resulting in not well formed "moved.vrt" file, that fails to load in QGIS after using the rasmover tool ("Layer failed to load!" as defined in the control you added in your code).

The wrong string is like

< GeoTransform >  -7533.658258,  8.0000000000000000e+01, 0.0000000000000000e+00, 101110.916867, 0.0000000000000000e+00,

that lacks the last parameter and lacks the closing </ GeoTransform> tag.

Resuming:
under Linux there is an issue with slashes/backslashes and with the code that replaces the 
< GeoTransform > tag/string from original.vrt to moved.vrt.

New tickets or is enough this comment?

**Comment by geodrinx** [comment]
Ciao Giovanni,
ho scritto un post nel mio blog, riguardante rasmover, con un breve video  :
http://exporttocanoma.blogspot.it/2014/12/rasmover-plugin-per-qgis.html
Domanda:  che tipo di coordinate stai usando ?  Portoghesi ?   Sono entrambi i sistemi di riferimento (layer e progetto) definiti ?
Qualche centinaio di utenti sta usando il plugin su Windows.  Avrei bisogno di un tuo file di esempio per testare il tuo caso.

Scusa se ho parlato italiano, ma dato che lo siamo entrambi...  :)

A presto

Roberto

**Comment by gioman** [comment]
si sto usando dati portoghesi, ma non é un problema di dati. Su Windows il plugin funziona (ora vedo il post). Su Linux ci sono i due problemi descritti, che non mi paiono di Linux in se: la sostituzione che fai in original.vrt per ottenere moved.vrt non funziona bene, il tag < GeoTransform > non é chiuso ed é incompleto e risulta in un vrt corrotto (e per questo il plugin sembra non faccia niente). C'é poi il problema degli slah/backslah che da il problema python descritto nel primo post.

**Comment by geodrinx** [comment]
OK.    Aggiornato il plugin.

Funziona solo su Windows (per ora).

Ciao

Roberto

**Comment by gioman** [comment]
Vuoi che ti apra i ticket per questi due problemi su Linux?

Ciao e grazie

**Comment by geodrinx** [comment]
Sì, grazie. 

Quando avró la possibilità di utilizzare una macchina Linux ci darò un'occhiata. 

R

**Comment by gioman** [comment]
Ti ho fatto una pull request con un paio di modifiche che sistemano questi due problemi su Linux. L'ho testata anche su Windows.
